In [ ]:
import numpy as np


### Exercicios:
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor



In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [ ]:
#1
np.sum(X)

136

In [ ]:
#2
np.mean(X)

8.5

In [ ]:
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#3 sem utilizar sum() and axis
c1 = np.sum(X[::,[0]])
c2 = np.sum(X[::,[1]])
c3 = np.sum(X[::,[2]])
c4 = np.sum(X[::,[3]])
print(c1,c2,c3,c4)

28 32 36 40


In [ ]:
#3 axis=0, a operação ao longo das linhas, resultando na soma para cada coluna.
np.sum(X, axis=0)

array([28, 32, 36, 40])

In [ ]:
#4 sem utilizar mean() and axis
l1 = np.mean(X[[0],::])
l2 = np.mean(X[[1],::])
l3 = np.mean(X[[2],::])
l4 = np.mean(X[[3],::])
print(l1,l2,l3,l4)

2.5 6.5 10.5 14.5


In [ ]:
#4 axis=1 significa que a operação será feita ao longo das colunas, resultando na média para cada linha.
np.mean(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [ ]:
#5
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
np.max(X)

10