In [1]:
import numpy as np
import pandas as pd


### Exercicios:
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor



In [2]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [3]:
#1
np.sum(X)

43

In [4]:
#2
np.mean(X)

4.777777777777778

In [5]:
X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
#3 sem utilizar sum() and axis
c1 = np.sum(X[::,[0]])
c2 = np.sum(X[::,[1]])
c3 = np.sum(X[::,[2]])
c4 = np.sum(X[::,[3]])
print(c1,c2,c3,c4)

28 32 36 40


In [7]:
#3 axis=0, a operação ao longo das linhas, resultando na soma para cada coluna.
np.sum(X, axis=0)

array([28, 32, 36, 40])

In [8]:
#4 sem utilizar mean() and axis
l1 = np.mean(X[[0],::])
l2 = np.mean(X[[1],::])
l3 = np.mean(X[[2],::])
l4 = np.mean(X[[3],::])
print(l1,l2,l3,l4)

2.5 6.5 10.5 14.5


In [9]:
#4 axis=1 significa que a operação será feita ao longo das colunas, resultando na média para cada linha.
np.mean(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [10]:
#5
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
np.max(X)

10

## Exercícios Aula 04
1. Resete o INDEX do dataframe transformado ele em Coluna exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
2. Crie um filtro para Kevin e Laura.
3. Crie um filtro para todos que tiveram um numero de tentativa(attempts) mair que 2.
4. Preencha os np.nan com 0.

In [11]:
# 1
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }

In [19]:
df = pd.DataFrame(exam_data)
df

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [21]:
#1
df_reset = df.reset_index()
df_reset

index       name  score  attempts qualify
0      0  Anastasia   12.5         1     yes
1      1       Dima    9.0         3      no
2      2  Katherine   16.5         2     yes
3      3      James    NaN         3      no
4      4      Emily    9.0         2      no
5      5    Michael   20.0         3     yes
6      6    Matthew   14.5         1     yes
7      7      Laura    NaN         1      no
8      8      Kevin    8.0         2      no
9      9      Jonas   19.0         1     yes

In [23]:
#2 Filtro para Kevin e Laura
filtro = df_reset[df_reset['name'].isin(['Kevin', 'Laura'])]
print(filtro_kevin_laura)


   index   name  score  attempts qualify
7      7  Laura    NaN         1      no
8      8  Kevin    8.0         2      no


In [28]:
#3 filtro para todos que tiveram um numero de tentativa(attempts) mair que 2
tentativas_maior_2 = df[df['attempts'] > 2]
tentativas_maior_2

name  score  attempts qualify
1     Dima    9.0         3      no
3    James    NaN         3      no
5  Michael   20.0         3     yes

In [31]:
#4 Preencha os np.nan com 0
df = df.fillna(0)

In [32]:
df

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    0.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    0.0         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes